# Generated by Django 5.2.16 on 2026-07-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='raw_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
