# Generated by Django 5.2.16 on 2026-07-30 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_candidate_raw_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('kind', models.CharField(blank=True, max_length=64)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('water_depth_m', models.FloatField(blank=True, null=True)),
                ('collected_at', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['site', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('region', models.CharField(blank=True, max_length=200)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['core', 'depth_cm', 'name']},
        ),
        migrations.AddField(
            model_name='slide',
            name='depth_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='core',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slides', to='viewer.core'),
        ),
        migrations.AddIndex(
            model_name='slide',
            index=models.Index(fields=['core', 'depth_cm'], name='viewer_slid_core_id_690347_idx'),
        ),
        migrations.AddField(
            model_name='core',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cores', to='viewer.site'),
        ),
        migrations.AddConstraint(
            model_name='core',
            constraint=models.UniqueConstraint(fields=('site', 'code'), name='uniq_core_code'),
        ),
    ]
