# Generated by Django 5.2.16 on 2026-08-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_slide_umpp_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='area',
            field=models.CharField(choices=[('ant', '남극'), ('kr', '한국')], default='ant', max_length=8),
        ),
    ]
