# Generated by Django 5.2.16 on 2026-08-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_site_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='area',
            field=models.CharField(choices=[('kr', '한국'), ('ant', '남극')], default='ant', max_length=8),
        ),
    ]
