# Generated by Django 5.2.16 on 2026-08-03 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_alter_site_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('group', 'group'), ('stack', 'stack'), ('detect', 'detect'), ('refilter', 'refilter'), ('reconcile', 'reconcile'), ('ingest', 'ingest'), ('export', 'export')], max_length=16)),
                ('label', models.CharField(max_length=120)),
                ('note', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'label'), name='uniq_batch_label')],
            },
        ),
        migrations.AddField(
            model_name='run',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='viewer.runbatch'),
        ),
    ]
