# Generated by Django 5.2.16 on 2026-08-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0009_runbatch_run_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='area',
            field=models.CharField(choices=[('kr', '한국'), ('ant', '남극')], db_default='ant', default='ant', max_length=8),
        ),
    ]
