# Generated by Django 5.2.16 on 2026-08-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0010_alter_site_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('running', 'running'), ('done', 'done'), ('partial', 'partial'), ('failed', 'failed')], default='running', max_length=8),
        ),
    ]
