# Generated by Django 5.2.16 on 2026-08-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0017_classdef_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='sample_kind',
            field=models.CharField(choices=[('core', '시추코어'), ('outcrop', '노두')], db_default='core', default='core', max_length=12),
        ),
    ]
