# Generated by Django 5.2.16 on 2026-08-05 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0018_slide_sample_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('stack', '합성본'), ('frame', '프레임'), ('depth', '깊이맵')], max_length=8)),
                ('path', models.CharField(max_length=500, unique=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('frame', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to='viewer.frame')),
                ('stack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='viewer.stack')),
                ('viewpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='viewer.viewpoint')),
            ],
            options={
                'ordering': ['viewpoint', 'kind', 'path'],
            },
        ),
        migrations.AddField(
            model_name='detection',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='viewer.image'),
        ),
        migrations.AddField(
            model_name='objectreview',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object_reviews', to='viewer.image'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['viewpoint', 'kind'], name='viewer_imag_viewpoi_4a205e_idx'),
        ),
    ]
