# Generated by Django 5.2.16 on 2026-08-05 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0019_image_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='viewpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='viewer.viewpoint'),
        ),
    ]
