# Generated by Django 5.2.16 on 2026-08-05 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0020_alter_image_viewpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='stack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='viewer.stack'),
        ),
    ]
