# Generated by Django 5.2.16 on 2026-08-09 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0029_batch_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='object_links', to='viewer.runbatch')),
                ('viewpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_links', to='viewer.viewpoint')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectLinkMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mask_key', models.CharField(max_length=64)),
                ('is_rep', models.BooleanField(db_default=False, default=False)),
                ('geom', models.JSONField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='viewer.runbatch')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_members', to='viewer.image')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='viewer.objectlink')),
            ],
        ),
        migrations.AddIndex(
            model_name='objectlink',
            index=models.Index(fields=['viewpoint'], name='viewer_obje_viewpoi_a7e604_idx'),
        ),
        migrations.AddIndex(
            model_name='objectlinkmember',
            index=models.Index(fields=['image', 'batch'], name='viewer_obje_image_i_eccd8c_idx'),
        ),
        migrations.AddConstraint(
            model_name='objectlinkmember',
            constraint=models.UniqueConstraint(fields=('link', 'image'), name='uniq_linkmember_image'),
        ),
        migrations.AddConstraint(
            model_name='objectlinkmember',
            constraint=models.UniqueConstraint(condition=models.Q(('batch__isnull', False)), fields=('image', 'batch', 'mask_key'), name='uniq_linkmember_key'),
        ),
        migrations.AddConstraint(
            model_name='objectlinkmember',
            constraint=models.UniqueConstraint(condition=models.Q(('batch__isnull', True)), fields=('image', 'mask_key'), name='uniq_linkmember_manual'),
        ),
        migrations.AddConstraint(
            model_name='objectlinkmember',
            constraint=models.UniqueConstraint(condition=models.Q(('is_rep', True)), fields=('link',), name='uniq_linkmember_rep'),
        ),
    ]
