# Generated by Django 5.2.16 on 2026-08-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0032_diatom_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='diatomobject',
            name='pose',
            field=models.CharField(blank=True, choices=[('valve', 'valve view'), ('girdle', 'girdle view'), ('other', 'other position')], db_default='', default='', max_length=8),
        ),
        migrations.AddField(
            model_name='objectreview',
            name='grade',
            field=models.CharField(blank=True, choices=[('A', 'A — 동정키도 완형도 잘 드러난다'), ('B', 'B — 완형이나 형태가 덜 드러난다 · 또는 상태가 나쁘나 동정키가 남았다'), ('C', 'C — 완형도 동정키도 잘 안 드러난다')], db_default='', default='', max_length=1),
        ),
    ]
