# Generated by Django 5.2.16 on 2026-08-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    # **`0033` 이 둘이 될 뻔했다.** 109(`auto_confirmed`)가 같은 번호로 먼저
    # 들어와서, 둘 다 `0032` 에 매달면 잎이 둘이 되어 Django 가 멈춘다
    # ("Conflicting migrations detected"). 병합 마이그레이션을 따로 두는 대신
    # **뒤로 물러 줄로 세운다** — 둘 다 칼럼을 더하기만 해서 순서가 뜻을 안 바꾼다.
    dependencies = [
        ('viewer', '0033_objectreview_auto_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='diatomobject',
            name='pose',
            field=models.CharField(blank=True, choices=[('valve', 'valve view'), ('girdle', 'girdle view'), ('other', 'other position')], db_default='', default='', max_length=8),
        ),
        migrations.AddField(
            model_name='objectreview',
            name='grade',
            field=models.CharField(blank=True, choices=[('A', 'A — 동정키도 완형도 잘 드러난다'), ('B', 'B — 완형이나 형태가 덜 드러난다 · 또는 상태가 나쁘나 동정키가 남았다'), ('C', 'C — 완형도 동정키도 잘 안 드러난다')], db_default='', default='', max_length=1),
        ),
    ]
