"""코어 자료 표 둘을 세운다 — `CoreSeries` · `CorePoint` (P17 3절).

**더하기만 한다.** 있는 표를 하나도 안 건드리므로 되돌리면 표 둘이 없어질
뿐이다 — 자동 생성 그대로 두어도 되는 자리다(`0038` 과 같은 갈래. 063 이 당한
것은 이름을 바꾼 때였다).

**깊이가 `depth_mm` 정수인 이유**는 그것이 유일 제약의 열쇠여서다. XRF 가
1 mm 간격이라 cm 로 두면 열쇠가 부동소수가 되고, 다시 반입할 때 같은 점이 두
줄로 생길 수 있다. 화면과 축은 cm 로 말하고 바꾸는 자리는 `data.py` 하나다.

**자료는 여기 안 들어온다.** 반입은 `ops/import_coredata.py` 가 따로 하고 언제든
다시 돌릴 수 있다 — 마이그레이션에 실으면 배포마다 같은 값이 되어야 한다는 뜻이
되는데, 이 자료는 사람이 고쳐 가는 것이다.
"""
# Generated by Django 5.2.16 on 2026-08-19 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0038_atlas'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=80)),
                ('unit', models.CharField(blank=True, db_default='', default='', max_length=24)),
                ('source', models.CharField(choices=[('import', '반입'), ('manual', '수동')], db_default='import', default='import', max_length=12)),
                ('default_on', models.BooleanField(db_default=False, default=False)),
                ('sort_order', models.PositiveSmallIntegerField(db_default=100, default=100)),
                ('origin', models.CharField(blank=True, db_default='', default='', max_length=200)),
                ('note', models.TextField(blank=True, db_default='', default='')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_series', to='viewer.locality')),
            ],
            options={
                'verbose_name': '측정 항목',
                'ordering': ['locality', 'sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='CorePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth_mm', models.PositiveIntegerField()),
                ('value', models.FloatField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='viewer.coreseries')),
            ],
            options={
                'ordering': ['series', 'depth_mm'],
            },
        ),
        migrations.AddConstraint(
            model_name='coreseries',
            constraint=models.UniqueConstraint(fields=('locality', 'key'), name='uniq_core_series_key'),
        ),
        migrations.AddConstraint(
            model_name='corepoint',
            constraint=models.UniqueConstraint(fields=('series', 'depth_mm'), name='uniq_core_point_depth'),
        ),
    ]
