# Generated by Django 5.2.16 on 2026-08-26 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0040_object_anchor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('authors', models.CharField(max_length=64)),
                ('year', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('atlas', '도감'), ('paper', '논문')], db_default='paper', default='paper', max_length=8)),
                ('title', models.TextField(blank=True, db_default='', default='')),
                ('journal', models.CharField(blank=True, db_default='', default='', max_length=200)),
                ('note', models.TextField(blank=True, db_default='', default='')),
            ],
            options={
                'ordering': ['-year', 'authors'],
            },
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=40)),
                ('item_no', models.CharField(blank=True, db_default='', default='', max_length=16)),
                ('binomial', models.CharField(max_length=120)),
                ('region_raw', models.CharField(blank=True, db_default='', default='', max_length=64)),
                ('region', models.CharField(blank=True, db_default='', default='', max_length=64)),
                ('note', models.TextField(blank=True, db_default='', default='')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='viewer.reference')),
            ],
            options={
                'ordering': ['source', 'binomial'],
                'indexes': [models.Index(fields=['source'], name='viewer_occu_source_a700b1_idx'), models.Index(fields=['binomial'], name='viewer_occu_binomia_0456bb_idx'), models.Index(fields=['region'], name='viewer_occu_region_3270f2_idx')],
            },
        ),
    ]
