# Generated by Django 5.2.16 on 2026-08-31 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0041_reference_occurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='atlasplacement',
            name='crop_image',
            field=models.CharField(blank=True, db_default='', default='', max_length=200),
        ),
    ]
