# Generated by Django 5.2.16 on 2026-08-31 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0042_atlasplacement_crop_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binomial', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('accepted', '유효'), ('synonym', '이명'), ('absent', 'AlgaeBase 에 없다'), ('unassessed', '확인 필요/미확인')], max_length=16)),
                ('valid_name', models.CharField(blank=True, db_default='', default='', max_length=120)),
                ('source', models.CharField(blank=True, db_default='', default='', max_length=64)),
                ('note', models.TextField(blank=True, db_default='', default='')),
                ('checked', models.CharField(blank=True, db_default='', default='', max_length=32)),
            ],
            options={
                'verbose_name_plural': 'taxon names',
                'ordering': ['binomial'],
            },
        ),
    ]
